# from Python.Exceptions.File_Handling import file_path

# data = ["hello world", "hello databricks", "hello spark"]
#
# data_count = {}
# for each in data:
#     for j in each.split(" "):
#         print(j)
#         if j not in data_count.keys():
#             data_count[j] = 1
#         else:
#             data_count[j] += 1
# print(data_count)


# file4 = open("C:\\Users\Dell\Desktop\Azure data\long-doc.txt", mode='r')
# print(file4.read())
# file4.close()
#
# file = open(r"\Users\Dell\Desktop\Azure data\DataBricks\orders.csv",mode = "r")
# print(file)

# a = (3)*[4]
# print(a)

# val = [1,2,3,4,5,6]
#
# val_num = []
#
#
# for each in val:
#     num = 1
#     for j in val:
#         if each != j:
#             num *= j
#     val_num.append(num)
# print(val_num)


# val = [10,20,30,20,10]
# new_list = []
# for each in val:
#
#     if val.count(each) > 1 and each  not in new_list:
#         new_list.append(each)
#
# print(new_list)
#
# nw = list({x for x in val if val.count(x)>1})
# ndn = {x for x in val if val.count(x)>1}
# print(ndn)



str = 'a33b4c6' # a33 times,b 4 times, c 6times



